name: update-readme

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: head
          bundler-cache: true
      - name: Build README
        run: ruby update_readme.rb
      - name: Reduce README
        run: bundle exec "asciidoctor-reducer -o README.adoc README.adoc"
      - name: Reduce tag pages
        run: find tags/* -exec bundle exec "asciidoctor-reducer -o {} {}" \;
      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
            add: '-A'

